# Generated by Django 6.0 on 2025-12-10 21:00

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Про себе'),
        ),
    ]
