# Generated by Django 6.0 on 2025-12-10 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('owner', 'Власник'), ('administrator', 'Адміністратор'), ('moderator', 'Модератор'), ('vip', 'VIP'), ('member', 'Користувач'), ('banned', 'Заблокований')], max_length=50, unique=True, verbose_name='Назва ролі')),
                ('level', models.IntegerField(default=0, verbose_name='Рівень ієрархії')),
                ('color', models.CharField(default='secondary', max_length=20, verbose_name='Колір значка')),
                ('can_edit_any_post', models.BooleanField(default=False, verbose_name='Може редагувати будь-які пости')),
                ('can_delete_any_post', models.BooleanField(default=False, verbose_name='Може видаляти будь-які пости')),
                ('can_close_topics', models.BooleanField(default=False, verbose_name='Може закривати теми')),
                ('can_pin_topics', models.BooleanField(default=False, verbose_name='Може закріплювати теми')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='Може управляти користувачами')),
                ('can_manage_categories', models.BooleanField(default=False, verbose_name='Може управляти категоріями')),
                ('can_ban_users', models.BooleanField(default=False, verbose_name='Може блокувати користувачів')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Ролі',
                'ordering': ['-level'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.role', verbose_name='Роль'),
        ),
    ]
