# Generated by Django 6.0 on 2025-12-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_role_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_moderate_topics',
            field=models.BooleanField(default=False, verbose_name='Може модерувати теми'),
        ),
    ]
