# Generated by Django 6.0 on 2025-12-11 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_existing_topics_approved(apps, schema_editor):
    """Встановити всі існуючі топіки як схвалені"""
    Topic = apps.get_model('forum', 'Topic')
    Topic.objects.all().update(status='approved')


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_category_parent_alter_category_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'Схвалено'), ('reject', 'Відхилено')], max_length=20, verbose_name='Дія')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата дії')),
            ],
            options={
                'verbose_name': 'Дія модерації',
                'verbose_name_plural': 'Дії модерації',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата модерації'),
        ),
        migrations.AddField(
            model_name='topic',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_topics', to=settings.AUTH_USER_MODEL, verbose_name='Модератор'),
        ),
        migrations.AddField(
            model_name='topic',
            name='moderation_comment',
            field=models.TextField(blank=True, verbose_name='Коментар модератора'),
        ),
        migrations.AddField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує модерації'), ('approved', 'Схвалено'), ('rejected', 'Відхилено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['status', '-created_at'], name='forum_topic_status_5eed8d_idx'),
        ),
        migrations.AddField(
            model_name='moderationaction',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to=settings.AUTH_USER_MODEL, verbose_name='Модератор'),
        ),
        migrations.AddField(
            model_name='moderationaction',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_history', to='forum.topic', verbose_name='Тема'),
        ),
        migrations.RunPython(set_existing_topics_approved, reverse_code=migrations.RunPython.noop),
    ]
